name: Test deployment

on:
  pull_request:
    branches:
      - master

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Bigdata_Blog_Website
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: Bigdata_Blog_Website
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build